# Generated by Django 5.2.6 on 2026-09-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_chatmessage_onlinecourse_socialclick_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_alt_text', models.CharField(default='College Admission', max_length=100)),
                ('apply_popup_enabled', models.BooleanField(default=True)),
                ('auto_open_popup', models.BooleanField(default=True)),
                ('popup_title', models.CharField(default='Apply for Admission', max_length=120)),
                ('popup_message', models.CharField(default='Complete the short form for free counselling and application assistance.', max_length=240)),
                ('popup_delay_seconds', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AddField(
            model_name='college',
            name='college_type',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Law', 'Law'), ('Medical', 'Medical'), ('Pharmacy', 'Pharmacy'), ('General', 'General'), ('Other', 'Other')], default='General', max_length=30),
        ),
        migrations.AddField(
            model_name='college',
            name='university_group',
            field=models.CharField(choices=[('IPU', 'IPU Colleges'), ('MDU', 'MDU Colleges'), ('AKTU', 'AKTU Colleges'), ('KUK', 'KUK Colleges'), ('OTHER', 'Other Colleges')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Management', 'Management'), ('Computer Applications', 'Computer Applications'), ('Law', 'Law'), ('Media', 'Media'), ('Pharmacy', 'Pharmacy'), ('Medical', 'Medical'), ('Commerce', 'Commerce'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=40),
        ),
    ]
