# Generated by Django 5.2.6 on 2026-09-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_sitesettings_college_college_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='Licensed campus image URL, e.g. Wikimedia Commons'),
        ),
        migrations.AddField(
            model_name='college',
            name='image_source_url',
            field=models.URLField(blank=True, help_text='Original image/source page for attribution'),
        ),
        migrations.AddField(
            model_name='course',
            name='career_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='AI-generated or licensed course image URL'),
        ),
        migrations.AddField(
            model_name='course',
            name='image_source_url',
            field=models.URLField(blank=True, help_text='Credit/source page for external image'),
        ),
        migrations.AddField(
            model_name='course',
            name='motivation',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='onlinecourse',
            name='image_source_url',
            field=models.URLField(blank=True),
        ),
    ]
