# Generated by Django 5.2.6 on 2026-09-12 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_college_external_image_url_college_image_source_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('SMS', 'SMS')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField(help_text='Merge fields: {name}, {course}, {college}, {counsellor}')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(help_text='Unique mobile number used to prevent duplicate leads', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('SMS', 'SMS')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Queued', 'Queued'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Read', 'Read'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=180)),
                ('provider_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='admissions.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('error_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches_assigned', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Employee', 'Employee'), ('Agent', 'Agent'), ('Consultant', 'Consultant'), ('College', 'College')], default='Employee', max_length=20)),
                ('organisation', models.CharField(blank=True, max_length=140)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('can_import_leads', models.BooleanField(default=False)),
                ('can_export_leads', models.BooleanField(default=False)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
