# Generated by Django 5.2.6 on 2026-09-12 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_communicationtemplate_lead_uploaded_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='notify_assignee_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='notify_lead_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followup',
            name='notify_lead_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CRMApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(db_index=True, max_length=16)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crm_api_keys', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
