# Generated by Django 5.2.6 on 2026-09-12 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_followup_notify_assignee_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='outcome',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='lead',
            name='call_outcome',
            field=models.CharField(choices=[('Untouched', 'Untouched'), ('Connected', 'Connected'), ('Not Reachable', 'Not Reachable'), ('Busy', 'Busy'), ('Call Again', 'Call Again'), ('Parent Discussion', 'Parent Discussion'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('Visit Planned', 'Visit Planned'), ('Registered', 'Registered')], default='Untouched', max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New Enquiry', 'New Enquiry'), ('New', 'New'), ('First Call', 'First Call'), ('Contacted', 'Contacted'), ('Interested', 'Interested'), ('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Visit Planned', 'Visit Planned'), ('Counselling Booked', 'Counselling Booked'), ('Counselling Done', 'Counselling Done'), ('Documents Pending', 'Documents Pending'), ('Application Started', 'Application Started'), ('Application Submitted', 'Application Submitted'), ('Offer Issued', 'Offer Issued'), ('Fee Pending', 'Fee Pending'), ('Fee Paid', 'Fee Paid'), ('Registered', 'Registered'), ('Admission Confirmed', 'Admission Confirmed'), ('Closed', 'Closed'), ('Lost', 'Lost')], default='New Enquiry', max_length=30),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Created', 'Created'), ('Stage Changed', 'Stage Changed'), ('Call', 'Call'), ('Follow-up', 'Follow-up'), ('Note', 'Note'), ('Assignment', 'Assignment'), ('Communication', 'Communication'), ('Admission', 'Admission')], max_length=40)),
                ('description', models.TextField()),
                ('old_stage', models.CharField(blank=True, max_length=30)),
                ('new_stage', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='admissions.lead')),
            ],
        ),
    ]
