# Generated by Django 5.2.6 on 2026-09-12 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_followup_completed_at_followup_outcome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['completed', 'due_at'], name='admissions__complet_4a0d82_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['reminder_sent_at', 'due_at'], name='admissions__reminde_fdc923_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='admissions__status_1da006_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='admissions__assigne_2a1ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'created_at'], name='admissions__source_639d3c_idx'),
        ),
    ]
