# Generated by Django 5.2.6 on 2026-09-13 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_followup_admissions__complet_4a0d82_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='class_10_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='class_12_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='father_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('Website', 'Website'), ('Google Ads', 'Google Ads'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('WhatsApp', 'WhatsApp'), ('Phone Call', 'Phone Call'), ('Walk-in', 'Walk-in'), ('Referral', 'Referral'), ('YouTube', 'YouTube'), ('LinkedIn', 'LinkedIn'), ('Other', 'Other')], default='Website', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('Photograph', 'Photograph'), ('Signature', 'Signature'), ('Aadhaar Card', 'Aadhaar Card'), ('Class 10 Marksheet', 'Class 10 Marksheet'), ('Class 12 Marksheet', 'Class 12 Marksheet'), ('Entrance Scorecard', 'Entrance Scorecard'), ('Character Certificate', 'Character Certificate'), ('Migration Certificate', 'Migration Certificate'), ('Certificate', 'Certificate'), ('Resume', 'Resume'), ('Other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Super Admin', 'Super Admin'), ('Admission Manager', 'Admission Manager'), ('Counsellor', 'Counsellor'), ('Data Entry Operator', 'Data Entry Operator'), ('Staff', 'Staff'), ('Employee', 'Employee'), ('Agent', 'Agent'), ('Consultant', 'Consultant'), ('College', 'College')], default='Employee', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='admissions.lead')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Part Paid', 'Part Paid'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.studentapplication')),
            ],
        ),
        migrations.CreateModel(
            name='NurtureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Sent', 'Sent'), ('Partial', 'Partial'), ('Failed', 'Failed'), ('Skipped', 'Skipped')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurture_logs', to='admissions.lead')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lead', 'day'), name='unique_lead_nurture_day')],
            },
        ),
    ]
