# Generated by Django 5.2.6 on 2026-09-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_entranceexam_classroom_crmtask_employeerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='leads/%Y/%m/'),
        ),
    ]
